id: IC875844E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:41:06+00:00'
last_modified: '2022-06-09T07:24:03.409919+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7478
  title: རྒྱུད་ལུགས་འཇམ་དཔལ་ཞི་བའི་སྒྲུབ་ཐབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DB3E:
      image_group_id: I3CN7480
      title: Volume 1 of rgyud lugs 'jam dpal zhi ba'i sgrub thabs ye shes snang ba
        mchog grub/
      total_pages: 445
      order: 1
      base_file: DB3E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
