id: IC875844E
legacy_id: P007912
ocr_import_info:
  bdrc_scan_id: W3CN7478
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T13:38:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:35:48.601174+00:00'
last_modified: 2022-09-03 23:35:58.690540
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7478
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7478
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་ལུགས་འཇམ་དཔལ་ཞི་བའི་སྒྲུབ་ཐབས།
statistics:
  ocr_word_mean_confidence_index: 0.5939950849511068
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I3CN7480:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7480
      total_pages: 445
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7480.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5939950849511068
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
