id: P007912
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:47.544132
source_metadata:
  id: bdr:W3CN7478
  title: རྒྱུད་ལུགས་འཇམ་དཔལ་ཞི་བའི་སྒྲུབ་ཐབས།
  author: ''
  volumes:
    3b5c7f39a234438595e96fd914e5b688:
      image_group_id: I3CN7480
      title: Volume 1 of rgyud lugs 'jam dpal zhi ba'i sgrub thabs ye shes snang ba
        mchog grub/
      volume_number: 1
      total_pages: 445
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
