id: P007912
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7478
  title: རྒྱུད་ལུགས་འཇམ་དཔལ་ཞི་བའི་སྒྲུབ་ཐབས།
  author: ''
  volumes:
    936f5afb991041e3b7c1b1e042130832:
      image_group_id: I3CN7480
      title: ''
      volume_number: 1
      total_pages: 445
ebook_metadata:
  title: རྒྱུད་ལུགས་འཇམ་དཔལ་ཞི་བའི་སྒྲུབ་ཐབས།
  author: ''
  sku: P007912
  cover: cover.jpg
  layers:
  - pagination
